# Define la plataforma iOS y la versión mínima requerida
platform :ios, '15.0'

# Obtiene la ruta al directorio actual del Podfile
flutter_root = File.dirname(File.realpath(__FILE__))

# Evalúa el podhelper.rb de Flutter para instalar los Pods
eval(File.read(File.join(flutter_root, '..', '..', '..', '..', 'Developer', 'flutter', 'packages', 'flutter_tools', 'bin', 'podhelper.rb')), binding)

# Define el target para tu aplicación iOS (usando el nombre correcto del target)
target 'Runner' do
  # Indica que se usarán frameworks
  use_frameworks!

  # Define el path a la aplicación Flutter en iOS
  flutter_application_path = File.dirname(File.realpath(__FILE__))

  # Instala todos los Pods de Flutter para la aplicación iOS
  flutter_install_all_ios_pods flutter_application_path

  # Define el target de pruebas si es necesario
  target 'RunnerTests' do
    inherit! :search_paths
    # Aquí se pueden agregar Pods adicionales para pruebas si es necesario
  end
end

# Script post-install para configuraciones adicionales si es necesario
post_install do |installer|
  # Llama a la función de post-instalación de Flutter si está definida
  flutter_post_install(installer) if respond_to?(:flutter_post_install)
end